
A_COMMAND = "A_COMMAND"
C_COMMAND = "C_COMMAND"
L_COMMAND = "L_COMMAND"

M_DEST = "M"
A_DEST = "A"
D_DEST = "D"

JUMP_GREATER = "JGT"
JUMP_EQUAL = "JEQ"
JUMP_GREATER_EQUAL = "JGE"
JUMP_LESS_THAN = "JLT"
JUMP_NOT_EQUAL = "JNE"
JUMP_LESS_EQUAL = "JLE"
JUMP_UNCONDITIONAL = "JMP"